services:
  master:
    image: python_app_base
    ports:
      - 8000:8000
    environment:
      - SECONDARY_01_URL=http://secondary_01:8001
      - SECONDARY_02_URL=http://secondary_02:8002
    networks:
      - replicated-log-network
    entrypoint: ["uvicorn"]
    command: ["app_master:app", "--host=0.0.0.0", "--port=8000"]
  secondary_01:
    image: python_app_base
    ports:
      - 8001:8001
    networks:
      - replicated-log-network
    entrypoint: ["uvicorn"]
    command: ["app_secondary:app", "--host=0.0.0.0", "--port=8001"]
  secondary_02:
    image: python_app_base
    ports:
      - 8002:8002
    networks:
      - replicated-log-network
    entrypoint: [ "uvicorn" ]
    command: [ "app_secondary:app", "--host=0.0.0.0", "--port=8002" ]
networks:
  replicated-log-network:
    driver: bridge
